# Generated by Django 3.0.5 on 2020-05-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textevaluation',
            name='text_evaluated',
        ),
    ]
