# Generated by Django 3.0.5 on 2020-05-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brec', '0002_remove_textevaluation_text_evaluated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textevaluation',
            name='created_at',
        ),
    ]
